#此工作流会在创建发布时使用Twine上载Python包
#更多信息请参见：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#发布到包的注册表

#此工作流使用未经GitHub认证的操作。
#它们由第三方提供，并由
#单独的服务条款、隐私政策和支持
#documentation。

姓名:上传Python包

在……之上:
释放:
类型:[出版]

权限:
内容:读

工作:
部署:

run-on:ubuntu-最新

步骤:
-uses:操作/签出@v3
-姓名:设置Python
uses:actions/setup-python@v3
和……一起:
Python版:'3.x'
-姓名:安装相依性
跑:|
Python-m pip安装--upgrade pip
PIP安装组建
-姓名:生成包
跑:Python-m生成
-姓名:发布包
uses:Pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
和……一起:
用户:__令牌__
密码:${{secrets.PYPI_API_TOKEN}}
